# change source and team
source: https://github.com/rht-labs/tech-exercise.git
team: biscuits
release: ci-cd

applications:
  # Tooling to support CI/CD
  - name: ubiquitous-journey
    enabled: true
    helm_values:
      - ubiquitous-journey/values-tooling.yaml

  # Test app of app
  - name: test-app-of-pb
    enabled: true
    helm_values:
      - pet-battle/test/values.yaml

  # Staging App of Apps
  - name: staging-app-of-pb
    enabled: true
    helm_values:
      - pet-battle/staging/values.yaml
