---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy
spec:
  workspaces:
    - name: output
    - name: git-auth
  params:
    - name: APPLICATION_NAME
      description: Name of the application
      type: string
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
    - name: DEPLOY_ENVIRONMENT
      description: Environment to deploy the app
      type: string
    - name: TEAM_NAME
      description: Name of the team that doing this exercise :)
      type: string
    - name: VERSION
      description: Version of the application
      type: string
    - name: CHART_VERSION
      description: Version of the helm chart
      type: string
  steps:
    - name: patch-argo-conf
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/springdo/tekton-task-helm:3.6.3
      script: |
        #!/bin/sh
        yq eval -i .applications."$(params.APPLICATION_NAME)".source_ref=\"$(params.CHART_VERSION)\"  "$(params.DEPLOY_ENVIRONMENT)/values.yaml"
        yq eval -i .applications."$(params.APPLICATION_NAME)".values.image_version=\"$(params.VERSION)\" "$(params.DEPLOY_ENVIRONMENT)/values.yaml"
        yq eval -i .applications."$(params.APPLICATION_NAME)".values.image_namespace=\"$(params.TEAM_NAME)-$(params.DEPLOY_ENVIRONMENT)\" "$(params.DEPLOY_ENVIRONMENT)/values.yaml"
    - name: commit-changes
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/redhat-cop/ubi8-git:latest
      script: |
        #!/bin/sh
        # Commit the changes :P
        git config --global user.email "tekton@rht-labs.bot.com"
        git config --global user.name "🐈 Tekton 🐈"
        git config --global push.default simple
        git checkout main
        git add $(params.DEPLOY_ENVIRONMENT)/values.yaml
        git commit -m "🚀 AUTOMATED COMMIT - Deployment of $(params.APPLICATION_NAME) at version $(params.VERSION) 🚀" || rc=$?
        git remote set-url origin http://$(cat $(workspaces.git-auth.path)/username):$(cat $(workspaces.git-auth.path)/password)@gitlab-ce.do500-gitlab.svc.cluster.local/{{ .Values.team }}/tech-exercise.git
        git push -u origin main


