release: "staging"
helm_repository: "http://nexus:8081/repository/helm-charts/"

##############
# Argo Apps declaration
#############
applications:
  my_app:
    name: my-app
    enabled: true
    source_ref: 1.0.1 # helm chart version
    values:
      fullnameOverride: my-super-app
      image_version: 1.3.1
      image_namespace: labs-staging # over written by jenkins
  my-other-service:
    name: my-other-service
    enabled: true
    source_ref: 0.0.9 # helm chart version
    values:
      fullnameOverride: my-other-super-service
      image_version: 1.0.1
      image_namespace: labs-staging # over written by jenkins