release: "staging"

##############
# Argo Apps declaration
#############
applications:
  my_app:
    name: my-app
    enabled: true
    source_ref: 1.0.2 # helm chart version
    values:
      fullnameOverride: my-super-app
      image_version: 1.3.1
      image_namespace: labs-staging # over written by jenkins