apiVersion: v1
data:
  devworkspace.default_dockerimage.redhat-developer.web-terminal: |
    name: dev
    image: quay.io/eformat/stack-do500:latest
    memoryLimit: 512Mi
    args: [sleep, infinity]
    env:
    - name: DEVWORKSPACE_IDLE_TIMEOUT
      value: 1hr
    volumeMounts:
    - name: claim-devworkspace
      path: "/projects"
  devworkspace.idle_timeout: 8h
  devworkspace.routing.cluster_host_suffix: apps.hivec.sandbox1243.opentlc.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller
  namespace: openshift-operators
