---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-m2
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
spec:
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
