---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pet-battle-api-trigger-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-ref
      description: The full git ref
      default: master
    - name: git-repo-name
      description: The name of the deployment to be created / patched
    - name: git-branch
      description: The git branch name
    - name: git-short-revision
      description: Seven character git sha
    - name: git-app-of-apps-key
      description: App of Apps Key using lowercase
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: $(tt.params.git-repo-name)-
        labels:
          tekton.dev/pipeline: maven-pipeline
          git.branch: $(tt.params.git-branch)
          git.revision: $(tt.params.git-revision)
          git.short.revision: $(tt.params.git-short-revision)
        annotations:
          argocd.argoproj.io/sync-options: Prune=false
          argocd.argoproj.io/compare-options: IgnoreExtraneous
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: maven-pipeline
        # podTemplate:
          # securityContext:
          #   runAsNonRoot: true
          #   runAsUser: 1001
          #   fsGroup: 0
        params:
          - name: APPLICATION_NAME
            value: $(tt.params.git-repo-name)
          - name: GIT_URL
            value: http://gitlab-ce.gitlab.svc.cluster.local/{{ .Values.team }}/$(tt.params.git-repo-name).git
          - name: GIT_REVISION
            value: $(tt.params.git-revision)
          - name: GIT_SHORT_REVISION
            value: $(tt.params.git-short-revision)
          - name: GIT_REF
            value: $(tt.params.git-ref)
          - name: GIT_BRANCH
            value: $(tt.params.git-branch)
          - name: MAVEN_MIRROR_URL
            value: http://nexus:8081/repository/maven-public
          - name: BUILD_NAMESPACE
            value: "{{ .Values.team }}-ci-cd"
          - name: DEV_NAMESPACE
            value: "{{ .Values.team }}-dev"
          - name: TEST_NAMESPACE
            value: "{{ .Values.team }}-test"
          - name: STAGE_NAMESPACE
            value: "{{ .Values.team }}-staging"
          - name: MAVEN_BUILD_OPTS
            value:
              - -DskipTests
        workspaces:
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: build-images
        - name: maven-settings
          configmap:
            name: maven-settings
        - name: argocd-env-secret
          secret:
            secretName: argocd-token
        - name: maven-m2
          persistentVolumeClaim:
            claimName: maven-m2
        - name: git-auth-secret
          secret:
            secretName: git-auth
