applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "0.0.10"
    values:
      enabled: true
      bindings: &binds # this labs-devs is the GROUP NAME in IDM
        - name: labs-devs
          kind: Group
          role: edit
        # this labs-admins is the GROUP NAME in IDM
        - name: labs-admins
          kind: Group
          role: admin
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: labs-ci-cd
      namespaces:
        - name: labs-ci-cd
          bindings: *binds
        - name: labs-dev
          bindings: *binds
        - name: labs-test
          bindings: *binds
        - name: labs-staging
          bindings: *binds

  # Sealed Secrets
  
  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_ref: "0.0.15"
    values:
      service:
        name: nexus
  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.3"
    values:
      buildconfigs:
        # Jenkins S2I from Red Hat Labs
        - name: jenkins
          strategy_type: "Source"
          source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
          source_repo_ref: master
          source_context_dir: '/'
          builder_image_kind: "DockerImage"
          builder_image_name: quay.io/openshift/origin-jenkins
          builder_image_tag: "latest"
        # Jenkins agents for running builds etc
        # default names, versions, repo and paths set on the template
        - name: jenkins-agent-npm
        - name: jenkins-agent-mvn
        - name: jenkins-agent-graalvm
        - name: jenkins-agent-helm
        - name: jenkins-agent-argocd
      deployment:
        env_vars:
          - name: ARGOCD_CONFIG_REPO
            value: github.com/petbattle/ubiquitous-journey.git
          - name: GITHUB_ACCOUNT
            value: 'petbattle'
          - name: GITHUB_ORG
            value: 'true'
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123
