applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.0"
    operatorgroup: false # can refactor per project when https://github.com/redhat-cop/helm-charts/pull/183 merges
    values:
      serviceaccounts: ""
      bindings: &binds # do500-users is the GROUP NAME in IDM
        - name: do500-users
          kind: Group
          role: edit
        - name: jenkins
          kind: ServiceAccount
          role: admin
          namespace: biscuits-ci-cd
      namespaces:
        - name: biscuits-ci-cd
          bindings: *binds
        - name: biscuits-dev
          bindings: *binds
        - name: biscuits-test
          bindings: *binds
        - name: biscuits-staging
          bindings: *binds

  # Sealed Secrets
  - name: sealed-secrets
    enabled: false
    source: https://redhat-cop.github.io/helm-charts
    chart_name: helper-sealed-secrets
    source_ref: "1.0.1"
    values:
      secrets:
        - name: git-auth
          type: kubernetes.io/basic-auth
          labels:
            credential.sync.jenkins.openshift.io: "true"
          data:
            username: <YOUR_SEALED_SECRET_USERNAME>
            password: <YOUR_SEALED_SECRET_PASSWORD>

  # Nexus

  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-1.0.4"
    values:
      buildconfigs:
        # Jenkins S2I from Red Hat Labs
        - name: jenkins
          strategy_type: "Source"
          source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
          source_repo_ref: master
          source_context_dir: '/'
          builder_image_kind: "DockerImage"
          builder_image_name: quay.io/openshift/origin-jenkins
          builder_image_tag: "latest"
        # Jenkins agents for running builds etc
        # default names, versions, repo and paths set on the template
        - name: jenkins-agent-npm
        - name: jenkins-agent-mvn
        - name: jenkins-agent-helm
        - name: jenkins-agent-argocd
      deployment:
        env_vars:
          - name: ARGOCD_CONFIG_REPO
            value: ''
          - name: GITLAB_HOST
            value: ''
          - name: GITLAB_GROUP_NAME
            value: ''
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123

  # Tekton Pipelines
  - name: tekton-pipeline
    enabled: false
    source: https://git-cd..../tech-exercise.git
    source_ref: main
    source_path: tekton
    values:
      team: biscuits


# 2) we put this into the template for the ArgoApplication.yaml
#     # Tekton
#   - name: tekton-pipeline
#     enabled: true
#     source: https://git-cd..../tech-exercise.git
#     source_ref: "0.0.15"
#     helm_values:
#       - ubiquitous-journey/values-tooling.yaml