apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: maven-m2
    - name: git-auth
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_URL
    type: string
    default: ""
  - name: GIT_REVISION
    type: string
    default: "main"
  - name: GIT_REF
    type: string
    default: "refs/heads/main"
  - name: GIT_SHORT_REVISION
    type: string
    default: ""
  - name: GIT_BRANCH
    type: string
    default: ""
  - name: HELM_CHART_VERSION
    type: string
    default: ""
  - name: MAVEN_BUILD_OPTS
    description: maven build options
    type: array
    default: []
  - name: TEAM_NAME
    type: string
    default: "{{ .Values.team }}"
  - name: APP_OF_APPS_DEV_KEY
    type: string
    default: ""
  - name: APP_OF_APPS_TEST_KEY
    type: string
    default: ""
  - name: APP_OF_APPS_STAGE_KEY
    type: string
    default: ""
  tasks:
    - name: fetch-app-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_URL)"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: deleteExisting
          value: "true"
    - name: maven
      taskRef:
        name: maven
      params:
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
        - name: GOALS
          value:
            - "package"
        - name: MAVEN_BUILD_OPTS
          value:
            - "-Dquarkus.package.type=fast-jar"
            - "-DskipTests"
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: maven-m2
          workspace: maven-m2
        - name: output
          workspace: shared-workspace
      runAfter:
        - fetch-app-repository
    - name: bake
      taskRef:
        name: bake
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: TEAM_NAME
          value: "$(params.TEAM_NAME)"
        - name: VERSION
          value: "$(tasks.maven.results.VERSION)"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
      runAfter: 
        - maven
    - name: helm-package
      taskRef:
        name: helm-package
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: WORK_DIRECTORY
          value: "$(params.APPLICATION_NAME)/$(params.GIT_BRANCH)"
      runAfter: 
        - bake
    - name: fetch-argocd-configuration
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "http://gitlab-ce.do500-gitlab.svc.cluster.local/{{ .Values.team }}/tech-exercise.git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "tech-exercise/main"
        - name: deleteExisting
          value: "true"
      runAfter:
        - helm-package
    - name: deploy-test
      taskRef:
        name: deploy
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: git-auth
          workspace: git-auth
      params:
        - name: APPLICATION_NAME
          value: "$(params.APPLICATION_NAME)"
        - name: WORK_DIRECTORY
          value: "tech-exercise/main/pet-battle/"
        - name: DEPLOY_ENVIRONMENT
          value: "test"
        - name: TEAM_NAME
          value: "$(params.TEAM_NAME)"
        - name: VERSION
          value: "$(tasks.maven.results.VERSION)"
        - name: CHART_VERSION
          value: "$(tasks.helm-package.results.CHART_VERSION)"
      runAfter: 
        - fetch-argocd-configuration
  results:
    - name: VERSION
      description: Version of the application
      value: "$(tasks.maven.results.VERSION)"
    - name: CHART_VERSION
      description: Version of the helm chart
      value: "$(tasks.helm-package.results.CHART_VERSION)"
  